backend:
  name: github
  repo: Tyerlo/work-publication

media_folder: static/assets
public_folder: assets

collections:
  - name: jobs
    label: Jobs
    folder: content/jobs
    create: true
    editor:
      preview: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime, required: false }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
